name: my_final_web
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_my_final_web:
    path: rust_builder
  flutter_rust_bridge: 2.6.0
  provider: ^6.0.0
  english_words: ^4.0.0
  shelf_proxy: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/img/aniya.png