// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String getPlatformVersion() =>
    RustLib.instance.api.crateApiSimpleGetPlatformVersion();

List<Grade> fetchGrades({required String semester, required int studentId}) =>
    RustLib.instance.api
        .crateApiSimpleFetchGrades(semester: semester, studentId: studentId);

class Grade {
  final int courseId;
  final String courseName;
  final double score;
  final double gpa;
  final String semester;
  final int studentId;

  const Grade({
    required this.courseId,
    required this.courseName,
    required this.score,
    required this.gpa,
    required this.semester,
    required this.studentId,
  });

  @override
  int get hashCode =>
      courseId.hashCode ^
      courseName.hashCode ^
      score.hashCode ^
      gpa.hashCode ^
      semester.hashCode ^
      studentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Grade &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          score == other.score &&
          gpa == other.gpa &&
          semester == other.semester &&
          studentId == other.studentId;
}
